### ISSUE TITLE
Running app runtime in fullscreen doesn't go over the taskbar

### ISSUE THREAD

**Issue by beeb** [flexxui/webruntime#14]
Hey there!

I'm on Windows 10 and trying to show my flexx app in fullscreen. I tried to pass `windowmode='fullscreen'` or `windowmode='kiosk'` to my `app.launch('app'...)` call but I have a couple of issues:

 * Initially the "window" size is the default one (640x480 according to the webruntime source) even though it's borderless like it should.
 * If I minimize it by clicking the taskbar icon and click it again to display the window again, then it's the correct size (fullscreen) but Windows' taskbar is still visible.

Any help would be greatly appreciated! Thanks

**Comment by almarklein** [comment]
Hi @beeb I've transferred the issue to the appropriate library.

This is an interesting case, I've not used the `windowmode` feature a lot, to be honest, so this could be a bug. My initial feeling is that perhaps the size should not be specified in fullscreen/kiosk mode. Do you feel like looking into this yourself and perhaps make a PR? Otherwise I'll look into it when I have more time.

**Comment by beeb** [comment]
Hey! I'm not familiar with the code base and would lose a lot of time looking into this, so it's probably not efficient if I do it. I didn't set any `size` property in the case explained above, and this leads to the correct full-screen size, but only after minimizing and maximizing the window again. And in all cases the taskbar stays above it which is the main issue.

**Comment by almarklein** [comment]
I meant that the code in webruntime might need a change to not specify a width and height when fullscreen is requested.

**Comment by almarklein** [comment]
It's been a while :)  I applied a possible fix. I'll do a release today. Please re-open if the problem persists.
